server:
    port: 8080

spring:
    data:
        mongodb:
            host: 127.9.106.2
            port: 27017
            database: mytwiiiter
            username: admin
            password: dxKZq1EG1AeK
